services:
  go:
    container_name: go-chi-lambda
    volumes:
      - ./app:/app/
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
      # Development
      target: dev
    ports:
      - 8080:3000
    command: sh -c 'go mod tidy && air'